[lints]
workspace = true

[package]
name = "macos-module"

version.workspace = true
edition.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]
controls-module = { version = "*", path = "../controls-module" }
player-module = { version = "*", path = "../player-module" }

tokio.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
macos-now-playing = "0.1"
reqwest.workspace = true
