[package]
name = "macos-module"

version.workspace = true
edition.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]
controls-module = { version = "*", path = "../controls-module" }
player-module = { version = "*", path = "../player-module" }

tokio.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2.workspace = true
objc2-foundation.workspace = true
objc2-app-kit.workspace = true
objc2-core-foundation.workspace = true
objc2-media-player.workspace = true
block2.workspace = true
dispatch2.workspace = true
reqwest.workspace = true
