[lints]
workspace = true

[package]
name = "mpris-module"
version.workspace = true
edition.workspace = true
license-file.workspace = true
repository.workspace = true

[dependencies]
controls-module = { version = "*", path = "../controls-module" }
player-module = { version = "*", path = "../player-module" }

num-traits.workspace = true
mpris-server = "0.10"
tokio.workspace = true
